//AUTOGENERATED via AtomixTools, do not update manually
import('./build/shared/blockchain/tokenAmount/tokenAmount.matcher.js');
import('./build/shared/core/chaiDependencies.matcher.js');

process.env['AX_UNITTEST'] = true;